services:
    devcontainer:
        image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
        volumes:
            - ../../.:/workspace:cached
            - ~/.ssh:/home/vscode/.ssh:ro
        command: sleep infinity
        env_file:
            - ./syncfusion-license.env

    diagram-persistence-service:
        build:
            context: ../../DiagramPersistenceService
            dockerfile: Dockerfile
        ports:
            - "8081:8080"